# pnpm-workspace.yaml
packages:
  # Current main application
  - 'GLX_App_files'
  # Future workspace packages (if needed)
  - 'packages/*'
  - 'apps/*'
  # Exclude common directories
  - '!**/node_modules/**'
  - '!**/dist/**'
  - '!**/build/**'
